### ISSUE TITLE
stacks node is not syncing

### ISSUE THREAD

**Issue by Parmanand0712** [stacks-network/stacks-blockchain-docker#130]
I have started stacks node by following documentation with latest update and now i am getting errors

stacks-blockchain      | INFO [1730698168.142209] [stackslib/src/net/p2p.rs:2777] [p2p-(0.0.0.0:20444,0.0.0.0:20443)] IP address changed from None to Some((00000000000000000000ffff0a001f1c, 20444))
stacks-blockchain      | INFO [1730698168.195434] [stackslib/src/net/rpc.rs:556] [p2p-(0.0.0.0:20444,0.0.0.0:20443)] Handled StacksHTTPRequest, verb: GET, path: /v2/info, processing_time_ms: 0, latency_ms: 0, conn_id: 14, peer_addr: 172.18.0.3:39734, p2p_msg: None
stacks-blockchain-api  | {"level":"info","time":"2024-11-04T05:29:28.196Z","pid":19,"hostname":"d5b07787491c","name":"stacks-blockchain-api","component":"core-api","msg":"Connection to Stacks core node API server at: stacks-blockchain:20443"}
stacks-blockchain      | INFO [1730698169.888145] [stackslib/src/chainstate/nakamoto/coordinator/mod.rs:1058] [chains-coordinator-0.0.0.0:20443] Process burn block 827751 reward cycle 77 in /root/stacks-blockchain/data/mainnet/burnchain, in_prepare_phase: false, is_rc_start: true, is_prior_in_prepare_phase: true, burn_block_hash: 00000000000000000001db44472b58694960051eecc7e075dc6e89f85daf86df
stacks-blockchain      | ERRO [1730698169.888307] [testnet/stacks-node/src/main.rs:262] [chains-coordinator-0.0.0.0:20443] Process abort due to thread panic: panicked at /build/stackslib/src/chainstate/nakamoto/coordinator/mod.rs:311:5:
stacks-blockchain      | FATAL: called a nakamoto function outside of epoch 3
stacks-blockchain      | ERRO [1730698169.932744] [testnet/stacks-node/src/main.rs:264] [chains-coordinator-0.0.0.0:20443] Panic backtrace:    0: stacks_node::main::{{closure}}
stacks-blockchain      |              at build/testnet/stacks-node/src/main.rs:263:18
stacks-blockchain      |    1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
stacks-blockchain      |              at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/boxed.rs:2245:9
stacks-blockchain      |       std::panicking::rust_panic_with_hook
stacks-blockchain      |              at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:805:13
stacks-blockchain      |    2: std::panicking::begin_panic_handler::{{closure}}
stacks-blockchain      |              at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:664:13
stacks-blockchain      |    3: std::sys::backtrace::__rust_end_short_backtrace
stacks-blockchain      |              at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:170:18
stacks-blockchain      |    4: rust_begin_unwind
stacks-blockchain      |              at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
stacks-blockchain      |    5: core::panicking::panic_fmt
stacks-blockchain      |              at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
stacks-blockchain      |    6: blockstack_lib::chainstate::nakamoto::coordinator::get_nakamoto_reward_cycle_info
stacks-blockchain      |       blockstack_lib::chainstate::nakamoto::coordinator::<impl blockstack_lib::chainstate::coordinator::ChainsCoordinator<T,N,U,CE,FE,B>>::get_nakamoto_reward_cycle_info
stacks-blockchain      |              at build/stackslib/src/chainstate/nakamoto/coordinator/mod.rs:962:9
stacks-blockchain      |       blockstack_lib::chainstate::nakamoto::coordinator::<impl blockstack_lib::chainstate::coordinator::ChainsCoordinator<T,N,U,CE,FE,B>>::handle_new_nakamoto_burnchain_block
stacks-blockchain      |              at build/stackslib/src/chainstate/nakamoto/coordinator/mod.rs:1113:21
stacks-blockchain      |    7: blockstack_lib::chainstate::coordinator::ChainsCoordinator<T,N,U,CE,FE,B>::handle_new_burnchain_block
stacks-blockchain      |              at build/stackslib/src/chainstate/coordinator/mod.rs:2421:9
stacks-blockchain      |       blockstack_lib::chainstate::coordinator::ChainsCoordinator<T,blockstack_lib::chainstate::coordinator::comm::ArcCounterCoordinatorNotices,blockstack_lib::chainstate::coordinator::OnChainRewardSetProvider<T>,CE,FE,B>::handle_comms_epoch2
stacks-blockchain      |              at build/stackslib/src/chainstate/coordinator/mod.rs:599:19
stacks-blockchain      |    8: blockstack_lib::chainstate::coordinator::ChainsCoordinator<T,blockstack_lib::chainstate::coordinator::comm::ArcCounterCoordinatorNotices,blockstack_lib::chainstate::coordinator::OnChainRewardSetProvider<T>,CE,FE,B>::run
stacks-blockchain      |              at build/stackslib/src/chainstate/coordinator/mod.rs:565:21
stacks-blockchain      |    9: stacks_node::run_loop::neon::RunLoop::spawn_chains_coordinator::{{closure}}
stacks-blockchain      |              at build/testnet/stacks-node/src/run_loop/neon.rs:626:17
stacks-blockchain      |       std::sys::backtrace::__rust_begin_short_backtrace
stacks-blockchain      |              at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:154:18
stacks-blockchain      |   10: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
stacks-blockchain      |              at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/thread/mod.rs:522:17
stacks-blockchain      |       <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
stacks-blockchain      |              at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panic/unwind_safe.rs:272:9
stacks-blockchain      |       std::panicking::try::do_call
stacks-blockchain      |              at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:554:40
stacks-blockchain      |       std::panicking::try
stacks-blockchain      |              at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:518:19
stacks-blockchain      |       std::panic::catch_unwind
stacks-blockchain      |              at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panic.rs:345:14
stacks-blockchain      |       std::thread::Builder::spawn_unchecked_::{{closure}}
stacks-blockchain      |              at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/thread/mod.rs:521:30
stacks-blockchain      |       core::ops::function::FnOnce::call_once{{vtable.shim}}
stacks-blockchain      |              at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
stacks-blockchain      |   11: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
stacks-blockchain      |              at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/boxed.rs:2231:9
stacks-blockchain      |       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
stacks-blockchain      |              at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/boxed.rs:2231:9
stacks-blockchain      |       std::sys::pal::unix::thread::Thread::new::thread_start
stacks-blockchain      |              at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/pal/unix/thread.rs:105:17
stacks-blockchain      |   12: <unknown>
stacks-blockchain      |   13: __clone
stacks-blockchain      | 
stacks-blockchain      | Dumping core for pid 1
stacks-blockchain exited with code 1

root@emerging-stag:~# docker ps
CONTAINER ID   IMAGE                                     COMMAND                  CREATED          STATUS                          PORTS                                       NAMES
13618023f2fe   blockstack/stacks-blockchain:3.0.0.0.0    "/bin/stacks-node st…"   57 minutes ago   Restarting (1) 58 seconds ago                                               stacks-blockchain
db30628abe56   postgres:15-alpine                        "docker-entrypoint.s…"   57 minutes ago   Up 57 minutes                   5432/tcp                                    postgres
d5b07787491c   hirosystems/stacks-blockchain-api:8.2.0   "docker-entrypoint.s…"   57 minutes ago   Up 57 minutes                   0.0.0.0:3999->3999/tcp, :::3999->3999/tcp   stacks-blockchain-api

**Comment by xinzhongyoumeng** [comment]
We meet the same question. My node versoin is below (and we see the signer is not necessary, so we don't run the signer) :
```
STACKS_BLOCKCHAIN_VERSION=3.0.0.0.0
STACKS_BLOCKCHAIN_API_VERSION=8.2.0
POSTGRES_VERSION=16.4-alpine
```

**Comment by Parmanand0712** [comment]
My Node is running on below version

STACKS_BLOCKCHAIN_VERSION=3.0.0.0.0
STACKS_BLOCKCHAIN_API_VERSION=8.2.0
POSTGRES_VERSION=15-alpine

Is it okay to continue with the current PostgreSQL version, or do I need to update it?

If an update is required, what steps should I follow to perform the upgrade?
